<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('IpVerwaltung')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/media/css/style.css','screen')
                        ->prependStylesheet($this->basePath() . '/media/css/menu.css','screen')
                        ; ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/media/js/jquery.js')
        ; ?>

    </head>
    <body id="id_body">
        <div id="content">
            <?php if($this->Identity() !== NULL) { ?>
            <div id="div_header">
                <a href="<?php echo $this->url('web-home');?>" style="float:left">Home</a>
                <!--<a href="index.php" style="float:left">Help</a>-->
                <a href="<?php echo $this->url('web-auth-logout');?>" style="float:right">Logout</a>
            </div>
            <div id="div_menu">
                <h1>IP-Verwaltung</h1>
                <?php echo $this->navigation('navigation')->menu()->setUlClass('navigation');  ?>
            </div>
            <?php } ?>
            <?php if (isset($flashMessages)) : ?>
            <ul class="flash-messages">
                <?php foreach ($flashMessages as $message) : ?>
                <li> <?= $message; ?></li>
                <?php endforeach; ?>
            </ul>
            <?php endif; ?>
            <?php echo $this->content; ?>
        </div>

        <div id="mask" style="display: none;"></div>
        <div id="popup" style="display: none;"></div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
