<h1><?php echo $this->listname;?></h1>
<?php
$this->headScript()->appendFile($this->basePath() . '/media/js/jquery.dataTables.js');
$this->headLink()
    ->appendStylesheet($this->basePath() . '/media/css/jquery.dataTables.css','screen')
    ->appendStylesheet($this->basePath() . '/media/css/demo_table.css','screen')
;
?>
<table class="datatable">
    <thead>
    <tr>
        <?php
        foreach($this->headline as $head)
            echo "\t\t\t<th>$head</th>\n";
        ?>
    </tr>
    </thead>
    <tbody>
    <?php
    foreach($this->table as $row)
    {
        echo "\t\t<tr>\n";
        foreach($row as $col)
        {
            echo "\t\t\t<td>$col</td>\n";
        }
        echo "\t\t</tr>\n";
    }
?>
    </tbody>
</table>
<p>&nbsp;</p>
<div><a href="<?php echo $this->url('ipverwaltung-data-add',array('type'=>$this->type))?>">Add new</a></div>

<p>&nbsp;</p>

<p>&nbsp;</p>

<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
    $('.datatable').dataTable();
    } );
</script>
